[package]
name = "bigbalkanreader"
authors = ["HVCsano"]
version = "1.0.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tungstenite = "0.27.0"
